#pragma once
#include "NativeGameplayTags.h"

namespace FASGameplayTags
{
	// Abilities
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Melee);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_IsChanging);

	// Weapon state
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_IsFiring);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_None);

	// Weapon type
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Pistol);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Rifle);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_RocketLauncher);

	// Weapon GameplayCues
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Fire);
	
	// Character death
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	// Gameplay events that drive the death/respawn ability
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Respawn);
	
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Damage_Dealt);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Damage_Taken)

	// Effect payload data
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Momentum);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Healing);
	
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Lethal);
	
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Zone);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Zone_Head);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Zone_Body);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Zone_Limb);
	
	// Buffs
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Strength);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Resistance);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Vampire);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Reflect);

	// Damage classification
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Crit);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Reflected);

	// Buff GameplayCues
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Buff_Strength);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Buff_Resistance);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Buff_Vampire);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Buff_Reflect);
	
	//Ammo
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_Bullet);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_Energy);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_Rocket);
}
