#include "ASLogChannels.h"
DEFINE_LOG_CATEGORY(LogAS);
DEFINE_LOG_CATEGORY(LogAS_Ability);
DEFINE_LOG_CATEGORY(LogAS_Input);
DEFINE_LOG_CATEGORY(LogAS_Weapon);
DEFINE_LOG_CATEGORY(LogAS_Movement);
DEFINE_LOG_CATEGORY(LogProjectiles);