#pragma once
#include "NativeGameplayTags.h"

namespace ASUITags
{
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Layer_Game);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Layer_GameMenu);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Layer_Menu);
	ARENASHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Layer_Modal);
}
