;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.BlocksInteraction",DevComment="")
+GameplayTagList=(Tag="Ability.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Fire",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.IsChanging",DevComment="")
+GameplayTagList=(Tag="Gameplay.Zone.Body",DevComment="")
+GameplayTagList=(Tag="Gameplay.Zone.Head",DevComment="")
+GameplayTagList=(Tag="Gameplay.Zone.Limb",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Buff.Crits",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Buff.Reflect",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Buff.Resistance",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Buff.Vampire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.HitImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire.Pistol",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire.Railgun",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire.Rifle",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire.Shotgun",DevComment="")
+GameplayTagList=(Tag="Input.Ability2",DevComment="")
+GameplayTagList=(Tag="Input.PrimaryAbility",DevComment="")
+GameplayTagList=(Tag="Input.Weapon.Next",DevComment="")
+GameplayTagList=(Tag="Input.Weapon.Previous",DevComment="")
+GameplayTagList=(Tag="Input.Weapon.Slot.1",DevComment="")
+GameplayTagList=(Tag="Input.Weapon.Slot.2",DevComment="")
+GameplayTagList=(Tag="Input.Weapon.Slot.3",DevComment="")
+GameplayTagList=(Tag="Input.Weapon.Slot.4",DevComment="")
+GameplayTagList=(Tag="Input.Weapon.Slot.5",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="Weapon.Railgun",DevComment="")
+GameplayTagList=(Tag="Weapon.Railgun.HitCooldown",DevComment="")
+GameplayTagList=(Tag="Weapon.Rifle.Cooldown",DevComment="")
+GameplayTagList=(Tag="Weapon.RocketLauncher.Cooldown",DevComment="")
+GameplayTagList=(Tag="Weapon.Shotgun",DevComment="")

